name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Acionar Deploy no Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cv83vdij1k6c73bjpm90?key=C2CnB3mqChk"
